relalg2tex: remove unused compile-time dependency: project(':ingraph-cypher2relalg')
This created a circular dependency during "gradle test" and produced the following
suspicious error, while no Xtext was in use in the project ingraph-relalg2tex:

:ingraph-relalg2tex:generateXtext
java.lang.IllegalArgumentException: The 'no null' constraint is violated